questdb/questdb.io

docs/reference/configuration.md
This PR adds a section about logs in the configuration page.
=> docs(configuration): add section about logs - fix #160

docusaurus.config.js
This PR bumps QuestDB to 5.0.4 and the Helm chart to 0.2.5.
=> chore: bump QuestDB and Helm chart versions

src/pages/get-questdb.tsx
This fixes the release date being wrong on the questdb.io/get-questdb page.
=> fix: correct typo in Get QuestDB page

src/css/jumbotron.module.css, src/pages/index.tsx
A user reported that copying the `docker run -p...` line in the jumbotron after
a mouse selection produces an expected output when pasting:
`docker run -p 9000:9000 questdb/questdbDocker logo`
This PR makes the code element a block which prevent the mouse selection to
overflow to the icon.
=> fix(homepage): make the code element a block to prevent copy/paste overflow

blog/2020-10-16-taxi-drivers-are-options-traders.md
Add `og:image` tag for NYC taxis blog post.
=> fix(blog): add missing social meta tag to NYC taxis post

docusaurus.config.js, package.json, yarn.lock
This commit upgrades Docusaurus to 2.0.0 alpha 69. Facebook employees kindly fixed [an issue affecting us](https://github.com/facebook/docusaurus/issues/3584#issuecomment-732195755) and released a new version with the fix :tada:.
=> chore(deps): upgrade packages

docs/third-party-tools/kafka.md, sidebars.js
__Changes:__
* Removed Postgres config section
* Clean up one-liner example for publishing JSON messages with pretty example to demonstrate the schema
* Add better instructions for making `.jar` files available to Kafka
=> docs: improve Kafka page

blog/2020-12-10-building-a-garbage-free-network-stack-for-kafka-streams.md
* renamed file as there was a stray space instead of a hyphen in the markdown filename
* minor typo fixes
=> blog: remove space in md filename, typo fixes

package.json, yarn.lock
Before this commit, Docusaurus was generating duplicated "twitter:image"
metas, this was caused by a typo in Docusaurus. The problem was fixed
upstream [1].
We now use Docusaurus with the canary version that contains the fix.
[1] https://github.com/facebook/docusaurus/pull/3900
----
#
=> fix: update docusaurus to latest - dedup "twitter:image" metas

static/img/docs/diagrams/.railroad, static/img/docs/diagrams/sampleBy.svg
The `SAMPLE BY` diagram is missing a `T` property denoting Timestamp.
* `.railroad` EBNF file has been corrected
* updated the generated SVG to reflect the correction
=> docs: correct SAMPLE BY diagram with Timestamp, update .railroad EBNF

static/_redirects
Redirects do not work by pattern matching path segments and must be absolute URLs
=> chore: fix redirect with absolute URL to Grafana page

blog/2020-10-19-grafana-tutorial.md
The `ASOF JOIN` section should be omitted until crhttps://github.com/questdb/questdb/pull/736 lands on Docker:latest
=> docs(blog): comment out ASOF JOIN in grafana tutorial

blog/2020-12-10-garbage-free-stack-for-kafka-streams.md
Could not run `yarn start` due to broken keys in front matter
=> docs: fix broken front matter in Kafka post

static/_redirects
__Fixes:__
* Redirect needs to be updated for the new URL following the file rename in https://github.com/questdb/questdb.io/pull/296
=> docs: update redirects after blog post rename

src/theme/TutorialPostItem/index.tsx
Minor change, "bump" the title on tutorial page from h2 to h1.
=> fix: correct typo so a tutorial post contains an h1 title

static/_redirects
__Fixes:__
* Blog posts have the path segments in the format `YYYY-MM-DD-<title>` and tutorials should use `YYYY/MM/DD/<title>`
=> fix: update redirect path format for tutorials

static/_redirects
__Fixes:__
* Blog posts also use `YYYY/MM/DD/<title>` path format
=> fix: update redirects for tutorials

docs/reference/sql/fill.md, docs/reference/sql/sample-by.md
__Improvements:__
* Add FILL reference in SAMPLE BY page
* Minor cleanup to FILL docs
__Open Questions:__
closes https://github.com/questdb/questdb/issues/785
=> docs: update SAMPLE BY to reference FILL(fillOptions)

docs/develop/insert-data.md, docs/develop/query-data.md
__Web Console:__
The general introduction of the Web Console should happen at the Insert Data page rather than at the Query Data page. This PR moves recently-merged additions to the previous page so that it's in a more logical placement in terms of document order.
__Go formatting:__ 
To ease workflow on these pages, allowing Prettier to format Go examples using spaces instead of tabs as they are currently ignored in generated code blocks anyway.
=> docs: move Web Console details to insert data page, allow Prettier to format Go examples

docs/develop/insert-data.md, docs/third-party-tools/telegraf.md
Minor typo fix in Influx guide, reorder appearance of protocols
=> chore: typo fix, reorder appearance of TCP and UDP for Influx line

docs/reference/function/aggregation.md, docs/reference/function/date-time.md, docs/reference/function/meta.md, docs/reference/function/numeric.md, docs/reference/function/random-value-generator.md, docs/reference/function/row-generator.md, docs/reference/function/timestamp-generator.md
* Removed `Description` sections in favor of including this in the top-level description of a function to reduce redundant information
* Replaced section headings with bold text for:
* Examples
* Arguments
* Return Values
=> chore: improve readability of TOC in functions pages

docs/third-party-tools/kafka.md
There is a combination of `example-topic` and `example-events` used in the examples, this should be uniform.
=> chore: correct Kafka guide to use same topic

docs/reference/sql/case.md, docs/reference/sql/cast.md, docs/reference/sql/fill.md, docs/reference/sql/latest-by.md, docs/reference/sql/sample-by.md, docs/reference/sql/where.md
* To reduce confusion with the use of **timestamp**, columns demonstrating timestamp type are named `ts`.
* Once-over for example uppercase/lowercase in SQL and illustrative tables
=> docs: reword timestamp types in examples for consistency

docs/reference/sql/sample-by.md
* Add details when using `SAMPLE BY` after where clause with relative time range to now
closes #235
=> docs: add details for SAMPLE BY calculation

docs/develop/query-data.md
* `fmt` query parameter is not used on the `/exec` endpoint
=> docs: minor edit to python REST example

docs/reference/sql/create-table.md
The docs mention create table with special characters (space and period) should be done using single quotes. This is possible, but inserts must be done using double quotes. For the sake of consistency, change to double quotes and add insert example
=> docs: direct use of double quotes for tables with special characters

docs/reference/sql/alter-table-attach-partition.md
Detached partitions must be named `<partition_name>.detached` before executing SQL to attach.
=> docs: detached partitions must have explicit naming convention 

docs/develop/insert-data.md, docs/guides/influxdb-line-protocol.md
* Newline characters must be used as delimiters for ILP messages
* Python examples use TCP with hint for UDP sockets
=> chore: add details on newline delimiters for ILP messages

docs/guides/v6-migration.md, sidebars.js
This PR adds documentation for not-yet released functionality regarding table migrations. 
__background:__
Version 6.0 will upgrade tables to use a new transaction file format. This guide describes steps that can be taken by a user to manually downgrade tables for compatibility with earlier QuestDB versions.
=> docs: add guide for table migrations from 6 -> 5.x 

src/pages/careers.tsx
__Additions:__
The following two careers pages are now listed in "open positions" section
* Front end engineer
* Head of dev rel
=> chore: add job specs to careers page

src/assets/quotes.ts, src/css/enterprise/quote.module.css
The quotes should fit on a single line if possible, these changes make the author text slightly smaller to allow them to fit on one line in most screen sizes.
=> chore: update quote size in enterprise cards

src/pages/careers.tsx, src/pages/careers/developer-relations-engineer.mdx, src/pages/careers/head-of-developer-relations.mdx, src/theme/CareerEmailUs/index.tsx
* Adding dev rel engineer
* Highlighting dev rel engineer instead of __head of dev rel__ on careers page
* Pre-fill `mailto` subject line with role title
=> chore: Add dev rel engineer

docs/reference/api/java-embedded.md, docusaurus.config.js
This PR bumps the software version number and includes details on JDK versions for Maven users
=> chore: bump sv number for 6.0.0

docs/concept/designated-timestamp.md, docs/concept/partitions.md, docs/operations/capacity-planning.md, docs/reference/sql/create-table.md
Reference to O3 rejections is no longer applicable as of 6.0
=> chore: remove references to O3 rejections

docs/concept/designated-timestamp.md, docs/guides/hysteresis.md, docs/reference/api/java-embedded.md, docs/reference/function/conditional.md, docs/reference/function/date-time.md, docs/reference/function/meta.md, docs/reference/function/numeric.md, docs/reference/function/row-generator.md, docs/reference/function/text.md, docs/reference/function/timestamp-generator.md, docs/reference/function/timestamp.md, docs/reference/sql/show.md, docs/reference/sql/where.md, sidebars.js, src/css/community/page.module.css, static/img/docs/diagrams/whereRegexMatch.svg
This PR contains the following additions:
* `tables()` and meta functions updated with most recent example of returned rows, hints on checking designated timestamp
* regex operator usage changed from `~=(string, pattern)` to `string ~ pattern`
* additional hints to table metadata functions
* railroad diagram updates
* per-table hysteresis configuration `WITH <o3_config>`
=> update docs with table metadata functions, regex examples

blog/2021-05-10-questdb-release-6-0-tsbs-benchmark.md, docs/guides/v6-migration.md, docs/reference/function/date-time.md, docs/reference/sql/where.md, static/img/docs/diagrams/.railroad, static/img/docs/diagrams/whereTimestampPartial.svg, static/img/docs/diagrams/whereTimestampPartialModifier.svg
__Changes:__
For `WHERE timestamp = '2020-01-01'` is not a range, but a single timestamp of `2020-01-01T00:00:00.000000Z`. The new equivalent with the semantics 'all data for this day' using string equality is
```sql
WHERE timestamp IN '2020-01-01'
```
The string `2020-01-01` does not represent an interval, but a single `TIMESTAMP` data point of `2020-01-01T00:00:00.000000Z`
To check if data within an interval, use `BETWEEN` i.e.: 
```sql
WHERE timestamp BETWEEN '2020-01-01T00:00:00.000000Z' AND '2020-01-02T00:00:00.000000Z' 
```
=> docs: 6.0.1 timestamp changes

docs/get-started/docker.md, docs/introduction.md, docs/reference/configuration.md, docs/reference/function/numeric.md, docs/reference/operators/bitwise.md, docs/reference/sql/join.md, docusaurus.config.js, sidebars.js
__Additions:__
* `sqrt()` function for calculating the square root of a number
* `log()` function for calculating the natural logarithm of a number
* bitwise operators (`~` NOT , `^` XOR , `|` OR, `&` AND)
* details for Docker logging configuration, mounting local `conf/log.conf` file to a container
* `JOIN` execution order hints
__Fixes:__
* `qlog.conf` typo fixed to `/log-stdout.conf`
=> docs: 6.0.2 - bump QuestDB version, add log, sqrt, bitwise ops, Docker logging, JOIN

docs/develop/insert-data.md, docs/guides/influxdb-line-protocol.md, src/pages/index.tsx
__Minor corrections:__
* `send()` in ILP Python example should use `sendall()`
* `timestamp =` to `timestamp IN` on index
=> chore: sendall(), 'timestamp IN'

package.json, src/theme/prism-include-languages.js, yarn.lock
__Updates:__
Ran the following to upgrade SQL grammar to latest (1.0.7):
```bash
yarn upgrade @questdb/sql-grammar@1.0.7
```
This is evident as the `BETWEEN` keyword is not highlighted on master, see https://questdb.io/docs/reference/sql/where/#between
__Fixes:__
Updated Prism syntax highlighting on the docs to make way for the use of grammar used in questdb/sql-grammar which is passed as functions (DAY, MONTH, YEAR) - see https://github.com/questdb/sql-grammar/blob/master/src/functions.ts.
The regex used to match this on our docs expects parens following the function name. Now relaxed this to allow for grammar which ends in word boundary, i.e.:
```sql
--- matches
max()
MONTH
--- does not match
maxUncommitted...
```
=> chore: bump sql grammar to 1.0.7 for syntax highlighting

docs/get-started/docker.md, docs/guides/out-of-order-commit-lag.md, docs/operations/deployment.md, docs/reference/configuration.md
This PR aligns docker run commands across docs pages to publish all available ports.
=> docs: update docker commands to publish all ports

docusaurus.config.js
* QuestDB version 6.0.3
* helm chart - 0.8.0
=> docs: bump software versions for 6.0.3

docs/reference/sql/case.md, docs/reference/sql/fill.md
* Use uppercase for SQL keywords, correct typos in examples
=> chore: minor typo fixes, correct case

docs/guides/importing-data.md, docs/guides/out-of-order-commit-lag.md, docs/reference/function/aggregation.md, docs/reference/function/meta.md, docs/reference/sql/alter-table-set-param.md, docs/reference/sql/create-table.md, docs/reference/sql/insert.md, src/theme/prism-include-languages.js, static/img/docs/diagrams/.railroad, static/img/docs/diagrams/alterTableSetParam.svg, static/img/docs/diagrams/createTableWithCommitParam.svg, static/img/docs/diagrams/insert.svg
__Additions:__
* `first(sym_col)` first value in a symbol column
* `last(sym_col)` last value in a symbol column
__Changes:__
* `lag` as table parameter is now `commitLag`, examples and railroad diagrams now reflect this change
*  Lag takes `n*units` where `units` may be `us`, `s`, `h`, `d`, e.g.:
```sql
INSERT batch 100000 commitLag 180s INTO table
```
=> docs: add first(), last(), change 'lag' to 'commitLag'

docs/guides/working-with-timestamps-timezones.md, docs/reference/function/date-time.md, sidebars.js
This PR documents two functions available as of version [6.0.3](https://github.com/questdb/questdb/releases/tag/6.0.3) for converting timestamps to and from UTC.
=> docs: add to_utc() and to_timezone() functions

src/theme/Navbar/index.tsx, src/theme/Navbar/styles.module.css
Minor edit to the nav button to use the default `secondary` button style instead of hand-written values
=> chore: use theme's default secondary button style

netlify.toml
Currently, webpack cache on Netlify has older build vars which are not being updated, this PR disables caching of `node_modules/.cache` to trigger a full build
=> chore: disable caching node assets

docs/get-started/binaries.md
An older `{@version@}` variable is cached due to behavior documented in #493 , triggering page changes to force clean build of this page on Netlify.
=> chore: trigger changed page detection on Netlify

docs/operations/capacity-planning.md, docs/reference/api/influxdb.md, docs/reference/configuration.md
Removes/updates obsolete prop names in ILP docs and updates the defaults to actual values.
=> chore(docs): clean up ILP prop names and their defaults

docs/reference/command-line-options.md
In the 'https://questdb.io/docs/reference/command-line-options/' page, in the first table, in the description of Option '-t',  it we can replace 'If this option omitted' with 'if this option is omitted'. If you agree, please feel free to update.
- Current: If this option omitted.
- Suggestion: If this option is omitted. (I added 'is' to the sentence).
Thanks,
Pradeep.
=> Request to update typo

blog/2022-01-27-release-sql-jit-compiler.md, docs/introduction.md
In the Introduction page (https://questdb.io/docs/introduction/), 'LATEST BY' leads to 'LATEST ON' command information. Also, I read that 'LATEST BY' is deprecated. So, I updated the link text. Pls accept if you agree with this action.
=> Request to update LATEST BY to LATEST ON

docs/reference/function/numeric.md
Adds documentation for `power()` function along with relevant examples in the relevant section. 
Tested on local development setup.
Closes #1082.
=> [docs] Capture `power()` in docs/function/numeric

docs/reference/sql/order-by.md
I didn't bother with creating an issue for this typo... hopefully that's OK.
"Ressources" is the French spelling of "Resources". Also, typically in English it would be treated as an adjective, so it wouldn't be plural.
=> docs: correct spelling of resources

src/modules/cloud/CompareFeatures/index.tsx, src/modules/cloud/FeatureTable/styles.module.css
fixed overflowing tables at quest db cloud page. 
**before:**
**after:**
At smaller screen sizes (bellow 400px) the tables are overflowing due to some padding issue. i fixed it by removing the extra padding
=> fixed overflowing tables at quest db cloud page

src/css/community/page.module.css, src/pages/community.tsx
what i did is changed the default size of the image to `300px` and at `min-width: 800px` i changed it to `400px`
**before:**
**after:**
=> image overflow at swag page
