- .github/workflows/ci.yaml
- CODEOWNERS
> chore: add CODEOWNERS

- package.json
- scripts/image-min.js
- yarn.lock
> chore(build): resize images if width > 1920px or height > 1440px

- src/components/Feature/index.tsx
- src/components/Jumbotron/index.tsx
- src/components/Jumbotron/styles.module.css
> chore: update copy

- package.json
- scripts/check-size
- yarn.lock
> chore: add git hook to check and reject files larger than 10MB in static/img

- src/css/global.css
- src/pages/get-started.tsx
- static/_headers
- static/img/infima/arrow.svg
> chore: improve CSP rules + fix regression with Algolia

- blog/2020-08-06-my-journey-writing-questdb.md
- docs/reference/configuration/telemetry.md
- docs/reference/sql/except-intersect.md
- docs/reference/sql/group-by.md
- docusaurus.config.js
- package.json
- plugins/lint.js
- plugins/manifest.js
- src/css/global.css
- yarn.lock
> chore: remove inline bkg image + add ManifestPlugin + fmt docs & blog

- src/pages/get-started.tsx
> fix(get-started): correct typo in img path

- docs/api/java.md
Our current doc is incorrect anyway and using Java API with latest release is an absolute pain.
> docs: update embedded Java API reference

- docusaurus.config.js
- src/components/Head/index.tsx
- static/robots.txt
- types/global.d.ts
> chore: improve robots.txt + add missing meta tags

- blog/2020-07-22-influxdb-lp-on-tcp.md
- blog/2020-07-24-use-questdb-for-swag.md
> fix: correct typos in GitHub user names

- docusaurus.config.js
- plugins/body-tags.js
- plugins/fetch-release.js
- src/css/global.css
- src/theme/Layout/index.tsx
- src/theme/Layout/styles.module.css
> feat: add schema.org markup

- docusaurus.config.js
> chore: update to latest version, 5.0.3

- prettier.config.js
> fix(prettier): allow platform line endings, not just Linux

- README.md
- package.json
- scripts/pre-build.js
> chore: run prebuild script only on CI + clarify "build" in README

- README.md
- blog/2019-12-19-lineprot.md
- blog/2020-05-12-interesting-things-we-learned-about-sums.md
- blog/2020-06-15-python-questdb-tutorial.md
- blog/2020-07-01-we-put-a-sql-database-on-the-internet.md
- blog/2020-07-24-use-questdb-for-swag.md
- blog/2020-08-19-memory-mapping-deep-dive.md
- blog/2020-08-25-questitto.md
- docusaurus.config.js
- src/pages/getstarted.tsx
- src/pages/index.tsx
- src/theme/Navbar/index.tsx
- static/_redirects
- types/modules.d.ts
> refactor(links): remove "self" links + improve URLs for blog + shorten titles

- src/css/binary.module.css
> fix(getstarted): prevent overflow om mobiles - fixes #120

- src/theme/Footer/styles.module.css
> fix(footer): increase space between links

- blog/2020-06-15-python-questdb-tutorial.md
> fix(blog): correct typo in language name for Python/Jupyter blog post

- docusaurus.config.js
- package.json
- yarn.lock
> chore: update Docusaurus + generate sitemap without 301 redirections

- src/theme/AnnouncementBar/index.tsx
> fix: attempt to correct star rendering on Safari

- docs/reference/sql/join.md
> chore(docs): correct typo

- blog/2020-08-25-questitto.md
- docusaurus.config.js
> docs: update references to new Slack URL

- src/pages/careers/technical-content-writer.mdx
> fix(career): improve wording

- blog/2020-08-06-my-journey-writing-questdb.md
- docs/concept/storage-model.md
> chore: correct typos

- docs/develop/connect.md
- docs/develop/insert-data.md
- docs/develop/query-data.md
> docs: add example for NodeJS <> PG wire for insert

- docs/reference/function/aggregation.md
- docs/reference/function/date-time.md
- docs/reference/function/meta.md
- docs/reference/function/timestamp-generator.md
> docs: add section for haversine_dist_deg

- blog/2020-10-16-taxi-drivers-are-options-traders.md
Tweaks and fixes for the NYC taxis blog post, correction was 100% done by @NicQuestDB.
> blog: update NYC taxi drivers article (correction by @nicquestdb)

- docs/reference/sql/join.md
Document implicit joins in JOIN page.
> docs: add section about implicit joins - fix #161

- src/css/careers.module.css
- src/pages/careers/backend-software-engineer.mdx
- src/pages/careers/index.tsx
- src/pages/careers/technical-content-writer.mdx
> feat(careers): add new job spec

- blog/2020-06-15-python-questdb-tutorial.md
- blog/2020-10-16-taxi-drivers-are-options-traders.md
> chore: remove typos introduced by Prettier formatting

- src/css/case-study/jumbotron.module.css
- src/css/case-study/outcome.module.css
> fix: hardcode image size to prevent FOUC

- src/pages/case-study/toggle.tsx
- src/pages/customers/index.tsx
- src/pages/get-questdb.tsx
> chore(typos): update title/description for customers/case-study pages

- blog/2020-11-16-why-timeseries-data.md
> fix(blog): improve wording for "Why timeseries" post

- src/pages/case-study/toggle.tsx
> chore(toggle): correct typo in case study page

- src/css/_global.css
> fix: decrease space between a list "title" and its content

- src/css/case-study/jumbotron.module.css
- src/pages/case-study/toggle.tsx
- src/pages/customers/index.tsx
> feat(toggle): add link to toggle.global on company's logo

- src/css/_global.css
- src/css/customers/logo.module.css
- src/css/customers/quote.module.css
- src/css/index/docker.module.css
- src/css/index/menu.module.css
- src/css/index/showcase.module.css
- src/theme/Button/styles.module.css
> refactor(css): normalize transition durations

- blog/2020-11-16-why-timeseries-data.md
added links and reformated those paragraphs
> fix(blog): update wording on last post

- blog/2020-03-15-interthread.md
- blog/2020-04-02-using-simd-to-aggregate-billions-of-rows-per-second.md
- blog/2020-05-12-interesting-things-we-learned-about-sums.md
- blog/2020-07-22-influxdb-lp-on-tcp.md
- blog/2020-07-24-use-questdb-for-swag.md
- blog/2020-08-06-my-journey-writing-questdb.md
- blog/2020-08-19-memory-mapping-deep-dive.md
- blog/2020-10-16-taxi-drivers-are-options-traders.md
- blog/2020-10-20-authentication-for-influx-line-protocol.md
- blog/2020-11-16-why-timeseries-data.md
- src/css/_global.css
- src/css/get-questdb/binary.module.css
- src/css/get-questdb/cta.module.css
- src/pages/careers/index.tsx
- src/pages/case-study/toggle.tsx
- src/pages/customers/index.tsx
- src/pages/get-questdb.tsx
- src/pages/index.tsx
- src/theme/Banner/index.tsx
- src/theme/Banner/styles.module.css
- src/theme/DocPage/index.tsx
- src/theme/Layout/index.tsx
- src/theme/Screenshot/index.tsx
- src/theme/useMetadataContext.tsx
- tsconfig.json
> feat(blog): create and use new Banner component for posts

- src/css/_global.css
- src/css/section.module.css
> fix: correct regressions related to box model for sections and markdown styles

- package.json
> chore: opt-out from advanced CSS minification to prevent bugs

- src/theme/Navbar/styles.module.css
> fix: revamp integration of community links to prevent bugs on hover

- src/theme/Layout/index.tsx
- src/theme/Layout/styles.module.css
> fix: symlink PageLayout to Layout so it is used internally

- docs/reference/function/text.md
- docs/reference/sql/alter-table-drop-partition.md
- added new string functions (to_lowercase, to_uppercase)
- updated drop partition page
> docs: add new string functions + update drop partitions

- src/css/customers/logo.module.css
- src/pages/customers/index.tsx
Fixes https://github.com/questdb/questdb/issues/721
> feat(logos): change order + fix size + correct typos

- docs/third-party-tools/kafka.md
- sidebars.js
__Additions:__
* Documentation page for Kafka Connect via JDBC driver.
* Top-level sidebar navigation category for Third-Party Tools
> docs: add third-party tools category with Kafka

- blog/2019-12-19-lineprot.md
- blog/2020-03-15-interthread.md
- blog/2020-04-02-using-simd-to-aggregate-billions-of-rows-per-second.md
- blog/2020-05-12-interesting-things-we-learned-about-sums.md
- blog/2020-06-05-iot-on-questdb.md
- blog/2020-06-15-python-questdb-tutorial.md
- blog/2020-07-01-we-put-a-sql-database-on-the-internet.md
- blog/2020-07-22-influxdb-lp-on-tcp.md
- blog/2020-07-24-use-questdb-for-swag.md
- blog/2020-08-06-my-journey-writing-questdb.md
- blog/2020-08-19-memory-mapping-deep-dive.md
- blog/2020-10-16-taxi-drivers-are-options-traders.md
- blog/2020-10-19-grafana-tutorial.md
- blog/2020-10-20-authentication-for-influx-line-protocol.md
- blog/2020-11-16-why-timeseries-data.md
- blog/2020-11-26-http-server-contribution.md
> chore: add keywords to blog posts - #266

- blog/2020-12-10-building-a-garbage-free-network-stack-for-kafka-streams.md
* Improvements to the blog description field
* Introduction offers a high-level overview of topics that are covered
> docs: improve post description, introduction to Kafka blog post

- blog/2020-12-10-non-blocking-io-without-garbage-collection.md
- static/_redirects
* Renamed blog post with redirect rule
* Added more details in intro section with focus on garbage collection
> docs: rename blog on IODispatcher

- docs/develop/authenticate.md
- docs/develop/connect.md
- docs/develop/insert-data.md
- docs/develop/query-data.md
* Remove reference to `/query` entrypoint
* Improvement to examples
__TODO:__
> docs: improve insert data page / REST entrypoint

- blog/2020-12-10-garbage-free-stack-for-kafka-streams.md
- docs/concept/storage-model.md
- static/img/docs/concepts/columnUpdate.svg
__Fixes:__
* Missing square brakcet in Column Update SVG
* Exchanged column update and read diagrams
* Fix broken build with front matter in Kafka blog post
> docs: update storage model diagrams

- docs/develop/insert-data.md
- docusaurus.config.js
- src/theme/prism-include-languages.js
__Additions:__
* Improved Node.js Postgres examples:
* connection pooling
* parameterized queries
* prepared statements
* Added Rust example
* parameterized query
* prepared statement
* Enable specifying additional languages for syntax highlighting via Prism.js
> docs: improve PG examples, add support for rust

- docs/develop/insert-data.md
- docusaurus.config.js
- src/theme/prism-include-languages.js
The changes here are not yet on the latest release, let's revert and create a release branch
> chore: revert last commit

- src/pages/case-study/toggle.tsx
> chore: improve wording for customer page (Toggle)

- src/pages/enterprise.tsx
> chore: update wording

- src/assets/tutorials.ts
__Removed:__
* feature description article doesn't fit in tutorial category
> docs: minor edit to tutorial section

- docusaurus.config.js
> chore(footer): re-order elements`

- docusaurus.config.js
> chore: add SO URL to Community navigation dropdown

- tutorial/2020-06-05-iot-on-questdb.mdx
- tutorial/2020-06-15-python-questdb-tutorial.mdx
- tutorial/2020-08-25-questitto.mdx
This property will generate the preview image in the `/tutorial` page and will also generate the corresponding `og` meta.
> chore: add missing "image" front-matter prop

- docs/introduction.md
- docusaurus.config.js
__Additions:__
* SO added in Support section in Introduction
* Added SO link in footer element
closes #326
> chore: add SO links to support and footer element

- docs/introduction.md
- docs/operations/data-retention.md
- sidebars.js
- src/css/_global.css
__Additions:__
* data retention with examples for generating test data and dropping by date
~~__CSS Change:__~~
~~* Proposed reduction of vertical whitespace to improve readability~~
closes #243
> docs: add Data retention page

- docs/operations/health-monitoring.md
- docs/reference/configuration.md
We have an open issue (#197) which requires docs for health monitoring, this PR cleans up existing documentation. 
closes #197
> docs: minor improvements to health monitoring docs

- docs/introduction.md
- docs/third-party-tools/telegraf.md
* Removed `small` from screenshots in Telegraf article which restricted max size
* Added Telegraf page to introduction, ordered Third party tools section to match navigation
> docs: improve Telegraf screenshots + page to introduction

- docs/reference/function/date-time.md
__Additions:__
* `now()` in Date and Time functions
> feat: add now() function reference docs

- src/pages/index.tsx
- corrected some errors on landing page
- uppercase SQL statements for uniformity
> docs: multiple typo fixes

- docs/reference/function/conditional.md
- sidebars.js
__Additions:__
* Conditional functions page for `coalesce()`
> docs: add coalesce() function

- docs/reference/sql/create-table.md
__Changes:__
* Readability improvements on the `symbol` type which may have multiple optional parameters passed - this section needs to be easily navigated with attention to the overall document hierarchy.
* Minor typo fixes
> docs: revision of CREATE TABLE page

- docs/develop/insert-data.md
- docs/reference/api/rest.md
__Changes:__
* insert-data page has additional CURL with URL parameters and schema object
* REST API page has new examples showing curl with URL parameters and non-standard timestamp formats
> docs: clarify usage of schema and URL params using /imp endpoint

- docs/develop/insert-data.md
This PR adds a basic example using a socket connection to send records to QuestDB using Influx line protocol
> docs: add python example for ilp

- docs/introduction.md
These suggested changes make the introduction page more uniform in the presentation of information
> docs: rework intro to list sections with short description

- docs/develop/insert-data.md
- docs/develop/query-data.md
* Adds python for CSV import via REST
__TODO:__
> docs: add python snippets to import CSV file via REST

- docs/concept/designated-timestamp.md
* removed use of admonition blocks, improved readability of some sections
* examples in workarounds section easier to read with an improved description of the temporary table approach
> chore: minor revision to designated timestamp page

- docs/get-started/first-database.md
* Examples need minor adjustment to use a table alias (workaround for https://github.com/questdb/questdb/issues/865)
* minor cleanup, addition of missing `DROP TABLE` example
> docs: fix examples in 'create first database' guide, minor cleanup

- docs/guides/importing-data.md
- sidebars.js
* Adds a new sidebar element 'guides'
* Details on specifying text loader config
> chore: add text loader config

- src/pages/careers/backend-software-engineer.mdx
- src/pages/careers/front-end-engineer.mdx
- src/pages/careers/head-of-developer-relations.mdx
- src/pages/careers/senior-cloud-engineer.mdx
- src/pages/careers/technical-content-writer.mdx
* Adds "Working at QuestDB" section to all job specs
* Changes to frontend engineer spec
> chore: tidy up careers pages

- docs/guides/influxdb-line-protocol.md
- docs/reference/api/influxdb.md
- sidebars.js
Adds practical details of working with messages in InfluxDB line protocol
* general hints of message format
* data types
* naming conventions
__Open questions:__
closes #409
> chore: Add InfluxDB line protocol gui

- src/css/customers/logo.module.css
- src/css/index/customer.module.css
- src/pages/index.tsx
* Separate CSS module for index section
* use div instead of a elements
> chore: decouple styles from index and customer page modules

- src/assets/quotes.ts
> chore: add Ably quote

- src/css/index/customer.module.css
* justify logos center, increase spacing
> chore: use different alignment and spacing below breakpoint

- blog/2021-04-20-questdb-release-6-0-alpha.md
Point opengraph image to correct path, add opengraph image as banner for the post
> chore: add banner, point to opengraph image

- blog/2020-09-24-why-performance-matters.md
- blog/2020-11-26-why-timeseries-data.md
- docs/develop/insert-data.md
- docs/develop/query-data.md
- docs/operations/capacity-planning.md
* Insert data page has admonition block encouraging the use of ILP to load data
* Web Console is top suggested method for querying data
* fix for Nicholas' GitHub links
> chore: add admonition that users should use ILP as recommended ingestion method

- docs/guides/hysteresis.md
- docs/guides/importing-data.md
- docs/reference/sql/alter-table-set-param.md
- sidebars.js
- static/img/docs/diagrams/.railroad
- static/img/docs/diagrams/alterTable.svg
- static/img/docs/diagrams/alterTableSetParam.svg
* Minor changes to hysteresis guide
* Added `ALTER TABLE SET PARAM` docs
* Minor change to sidebar navigation, removed `Deploy QuestDB` from top-level nav as content is moved into separate docs
> docs: ALTER TABLE SET PARAM, out-of-order changes

- src/css/careers/job.module.css
- src/pages/careers/front-end-engineer.mdx
Fixes minor display issue when job title is too long and overflows to "Details" component
> chore: formatting, fix button text overflow

- docs/reference/sql/create-table.md
- static/img/docs/diagrams/.railroad
- static/img/docs/diagrams/createTable.svg
__Updates:__
* Adding documentation to `CREATE TABLE` page for `IF NOT EXISTS` clause
* updated railroad diagrams
* applied uniform formatting to examples
> docs: add CREATE TABLE IF NOT EXISTS

- docs/guides/influxdb-line-protocol.md
This PR expands on the ILP guide with 
* details for the column types that QuestDB parses ILP messages as
* how to omit symbol types
* more example timestamps
> docs: add more details for ILP message format

- .github/workflows/lighthouse.yaml
- .github/workflows/lighthousesrc.json
This PR tests lighthouse score on Pull Requests
> chore: test lighthouse action

- docs/reference/function/conditional.md
Adds missing documentation for `nullif` function.
> feat(docs): add nullif function

- src/pages/careers.tsx
- src/pages/careers/developer-in-test.mdx
This PR adds a developer in test spec
> chore: add Developer in Test spec

- blog/2020-07-01-we-put-a-sql-database-on-the-internet.md
> docs: Update 'inter-thread messaging' blog link

- blog/2022-01-27-release-sql-jit-compiler.md
- docs/reference/sql/latest-on.md
**Note** - Pls ignore 'blog/2022-01-27-release-sql-jit-compiler.md' in the 'Files changed' tab. It is displayed by mistake.
> docs: Update 'LATEST ON' page for better readability

- src/pages/community.tsx
Signed-off-by: SRIHARI S <sshsrn@gmail.com>
> Updated community page UI

- src/css/customers/quote.module.css
- src/css/enterprise/quote.module.css
fixed chevron overflowing 
**before:**
**after:**
Enterprise page :
**before:**
**after:**
> fixed customer success quotes overflow

- docs/get-started/docker.md
- src/theme/Footer/index.tsx
- src/theme/Footer/styles.module.css
made footer more good by adjusting some spacing 
**before:**
**after:**
now it looks more good and gives more space to breath.
> updated footer, changed spacing
